### ISSUE TITLE
width=100% will not work with the new admin of Django 4

### ISSUE THREAD

**Issue by anhtran** [django-ace/django-ace#28]
Because parent CSS class `flex-container` is a flexbox. So we need `django-ace-editor` grows all the remain space.

Just do this:

```css
.django-ace-editor {
    position: relative;
    flex: 1;
}
```
